name: tudatBundleCI
# adapted from:
# https://github.com/jherico/starter-workflows/blob/master/ci/cmake.yml
# and https://github.com/onqtam/doctest/pull/285/files

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [
          ubuntu-gcc,
          ubuntu-clang,
        ]

        include:
        - name: ubuntu-gcc
          os: ubuntu-latest
          compiler: gcc

        - name: ubuntu-clang
          os: ubuntu-latest
          compiler: clang

    steps:
    - uses: actions/checkout@v1

    - name: Clone Submodules
      shell: bash
      run: git submodule update --init --recursive

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Set Compiler Environment
      shell: bash
      run: |
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          echo "::set-env name=CC::gcc"
          echo "::set-env name=CXX::g++"
        else
          echo "::set-env name=CC::clang"
          echo "::set-env name=CXX::clang"
        fi

    - name: Configure CMake linux
      if: ( contains(matrix.os, 'ubuntu') )
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBoost_NO_BOOST_CMAKE=TRUE -DCMAKE_SH="CMAKE_SH-NOTFOUND"

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake --build . --target all --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE
